### PR TITLE
Parse expiry time without full ID token verification

### PR DESCRIPTION
**Pull request by odsod**
VerifyGoogleIDToken uses a cached verifier and needs refactoring to work
with multiple audiences.

This change allows the IDTokenSource to generate tokens for multiple
audiences, by not delegating to the VerifyGoogleIDToken function to
extract expire time.

### CODE REVIEW

**Comment by odsod** [comment]
Hi @salrashid123 ! Thanks for creating this library, it's enabled us to start experimenting with gRPC microservices on Cloud Run. Here's a fix for an issue we've run into when attempting to commuticate with multiple upstream services. Cheers

**Comment by salrashid123** [comment]
thanks for the PR.

Comment inline but maybe just as an arg?

```golang
func VerifyGoogleIDToken(ctx context.Context, token string, aud string, useCache bool) 
```

**Comment by odsod** [comment]
@salrashid123 I see what you mean, but the only call-site right now is:

https://github.com/salrashid123/oauth2/blob/master/google/idtoken.go#L245

```go
	idt, err := VerifyGoogleIDToken(context.Background(), idToken, ts.audiences[0])
	if err != nil {
		log.Fatalf("salrashid123/oauth2/google: Unable to verify OIDC token %v", err)
	}
```

and it would need to be called with `false` as a constant to resolve the issue.

What do you think about not calling `VerifyGoogleIDToken` from within the per-RPC token generator, and just parsing out the expiry time like this instead:

```go

func parseTokenExpiry(token string) (_ time.Time, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("parse token expiry: %w", err)
		}
	}()
	parts := strings.Split(token, ".")
	if len(parts) < 2 {
		return time.Time{}, fmt.Errorf("malformed JWT")
	}
	payload, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return time.Time{}, fmt.Errorf("decode payload: %w", err)
	}
	var claims struct {
		Expiry int64 `json:"exp"`
	}
	if err := json.Unmarshal(payload, &claims); err != nil {
		return time.Time{}, fmt.Errorf("unmarshal claims: %w", err)
	}
	return time.Unix(claims.Expiry, 0), nil
}
```

**Comment by salrashid123** [comment]
yeah, definately, i just was really lazy here so the section 
  https://github.com/salrashid123/oauth2/blob/master/google/idtoken.go#L245

should be the `parseTokenExpiry` as you've just written (pls feel free to add that in the PR!).
(meaning i had no reason to verify the token at all in the code)

The original intent for `VerifyGoogleIDToken` is intentionally exportable so anyone that uses it repeatedly and stillspecify the tokens.  

would it meet your needs to simply do the parsing of the expiry as i should have from the get-go?

---

btw, if your'e using other languages and id-tokens:  https://github.com/salrashid123/google_id_token

**Comment by odsod** [comment]
@salrashid123 I reformulated the PR so that we don't have to change (i.e. break) the API of VerifyGoogleIDToken right now. The new proposed change parses the expire time without calling VerifyGoogleIDToken, which should fix the issue we're having with generating tokens for multiple audiences.

Worth mentioning though that as part of fixing this issue, we've found that, for us, the the simplest solution to per-RPC token generation is to use the iam/credentials gRPC client to generate tokens. The only caveat being that the service account needs `roles/iam.serviceAccountTokenCreator` on its own service account - but as long as we grant that role, we get a simple token generator that works both locally and in the managed runtime.

```go
type TokenSourceConfig struct {
	ServiceAccount string
	Audience       string
}

func NewTokenSource(
	ctx context.Context,
	client *credentials.IamCredentialsClient,
	config TokenSourceConfig,
) *TokenSource {
	return &TokenSource{ctx: ctx, client: client, config: config}
}

type TokenSource struct {
	ctx    context.Context
	client *credentials.IamCredentialsClient
	config TokenSourceConfig
}

func (i *TokenSource) Token() (_ *oauth2.Token, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("token source for %s with account %s: %w", i.config.Audience, i.config.ServiceAccount, err)
		}
	}()
	response, err := i.client.GenerateIdToken(i.ctx, &credentialspb.GenerateIdTokenRequest{
		Name:         "projects/-/serviceAccounts/" + i.config.ServiceAccount,
		Audience:     i.config.Audience,
		IncludeEmail: true,
	})
	if err != nil {
		return nil, err
	}
	expiry, err := parseTokenExpiry(response.Token)
	if err != nil {
		return nil, err
	}
	return &oauth2.Token{
		AccessToken: response.Token,
		Expiry:      expiry,
	}, nil
}
```

**Comment by salrashid123** [comment]
sgtm.

If you're using the IAMcredentials approach exclusively, the `ImpersonatedTokenSource` actually does that
- https://github.com/salrashid123/oauth2#usage-impersonatedcredentials

which i think you can also pass as a type of `TokenSource` into the `IdTokenSource`
but if its easier, just use direct implementation (eg, fork) as you've done w/o going though all the other steps prior.  

anyway, with IAMcredentials, consider a custom role as opposed to tokencreator (the latter give a lot more permissions than necessary).    

custom_role


---

I sure you know of this but for any other reader i'll point out that  ifyou've got a cloud run's servcie account locally as a `json` cert file, you can use `GOOGLE_APPLICATION_CREDENTIALS` env var to point to it and still just use  the same code locally/remotely via 
https://github.com/salrashid123/oauth2#default-credentials-with-serviceaccount

**Pull request merged**
